import Loader from "@/components/Loader";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <html lang="en">
              <body>{children}</body>
            </html>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
